name:                aoc2020-haskell
version:             0.1.0.0
github:              "githubuser/aoc2020-haskell"
license:             BSD3
author:              "Matthew Green"
maintainer:          "mgreen89@gmail.com"
copyright:           "2020 Matthew Green"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mgreen89/aoc2020-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- criterion
- deepseq
- lens
- linear
- megaparsec >= 8.0
- monad-loops
- mtl
- parsec >= 3.0
- parser-combinators
- primitive
- split
- vector

library:
  source-dirs: src

default-extensions:
  - TupleSections

executables:
  aoc2020-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020-haskell

tests:
  aoc2020-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020-haskell
